In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.random.randn(100)
#making random numbers in array form

In [3]:
A

array([ 0.48164562,  1.52749035, -1.18853507, -0.21189823,  1.77363631,
        0.67749919, -0.40219946,  1.23172812, -0.42110475,  0.09506128,
       -0.52668163, -0.8293423 , -0.81601089,  0.99150816,  1.84937939,
        1.11260927,  0.01379548, -0.17727304, -2.65775591,  0.2243694 ,
       -1.34148341,  0.34564918, -0.02701912,  0.74334675,  0.33045811,
       -0.56479262, -0.73303561, -0.70700087, -0.38348743, -0.84541405,
        0.06694865, -1.08001904, -0.12470625,  0.53089335,  0.52491148,
       -1.8695841 , -0.05890619, -0.00607874, -1.63536087, -0.45198153,
        0.08333397,  0.33669716,  0.80717547, -0.95092347,  0.83387451,
        0.29847654,  0.16638455,  1.43909457, -1.25855383,  0.00915073,
       -0.17813823, -0.64644694, -0.71403323, -0.32433806, -0.29222559,
        0.92108953,  0.59551043,  0.36022011, -0.22193795, -0.47064882,
       -1.68544755,  0.49635766, -1.08036201, -0.56042483, -0.02385167,
        1.24341435, -0.27445544,  0.45404302,  0.17827135,  0.35

In [5]:
A = 10*A + 50
#formating A's value

In [6]:
A

array([54.81645617, 65.27490345, 38.11464926, 47.88101766, 67.73636312,
       56.77499191, 45.97800543, 62.31728116, 45.78895252, 50.95061279,
       44.73318373, 41.70657703, 41.83989114, 59.91508164, 68.49379393,
       61.12609265, 50.13795479, 48.22726963, 23.42244092, 52.24369398,
       36.58516587, 53.45649176, 49.7298088 , 57.4334675 , 53.3045811 ,
       44.35207378, 42.66964387, 42.92999129, 46.1651257 , 41.54585948,
       50.66948648, 39.19980958, 48.75293747, 55.30893346, 55.24911476,
       31.30415899, 49.41093806, 49.93921265, 33.64639126, 45.48018472,
       50.83333973, 53.36697161, 58.07175475, 40.49076531, 58.33874508,
       52.98476539, 51.66384553, 64.39094568, 37.41446168, 50.09150726,
       48.21861766, 43.53553056, 42.85966765, 46.75661943, 47.07774412,
       59.21089531, 55.95510433, 53.60220109, 47.78062046, 45.29351182,
       33.14552449, 54.96357663, 39.19637992, 44.39575171, 49.76148334,
       62.43414349, 47.25544557, 54.54043019, 51.78271348, 53.58

In [7]:
A.shape

(100,)

In [9]:
#Shaping A's presense
A.shape=(5,20)

In [10]:
A

array([[54.81645617, 65.27490345, 38.11464926, 47.88101766, 67.73636312,
        56.77499191, 45.97800543, 62.31728116, 45.78895252, 50.95061279,
        44.73318373, 41.70657703, 41.83989114, 59.91508164, 68.49379393,
        61.12609265, 50.13795479, 48.22726963, 23.42244092, 52.24369398],
       [36.58516587, 53.45649176, 49.7298088 , 57.4334675 , 53.3045811 ,
        44.35207378, 42.66964387, 42.92999129, 46.1651257 , 41.54585948,
        50.66948648, 39.19980958, 48.75293747, 55.30893346, 55.24911476,
        31.30415899, 49.41093806, 49.93921265, 33.64639126, 45.48018472],
       [50.83333973, 53.36697161, 58.07175475, 40.49076531, 58.33874508,
        52.98476539, 51.66384553, 64.39094568, 37.41446168, 50.09150726,
        48.21861766, 43.53553056, 42.85966765, 46.75661943, 47.07774412,
        59.21089531, 55.95510433, 53.60220109, 47.78062046, 45.29351182],
       [33.14552449, 54.96357663, 39.19637992, 44.39575171, 49.76148334,
        62.43414349, 47.25544557, 54.54043019, 5

In [13]:
A.reshape(4,25)
#New array, do not affect the original array

array([[54.81645617, 65.27490345, 38.11464926, 47.88101766, 67.73636312,
        56.77499191, 45.97800543, 62.31728116, 45.78895252, 50.95061279,
        44.73318373, 41.70657703, 41.83989114, 59.91508164, 68.49379393,
        61.12609265, 50.13795479, 48.22726963, 23.42244092, 52.24369398,
        36.58516587, 53.45649176, 49.7298088 , 57.4334675 , 53.3045811 ],
       [44.35207378, 42.66964387, 42.92999129, 46.1651257 , 41.54585948,
        50.66948648, 39.19980958, 48.75293747, 55.30893346, 55.24911476,
        31.30415899, 49.41093806, 49.93921265, 33.64639126, 45.48018472,
        50.83333973, 53.36697161, 58.07175475, 40.49076531, 58.33874508,
        52.98476539, 51.66384553, 64.39094568, 37.41446168, 50.09150726],
       [48.21861766, 43.53553056, 42.85966765, 46.75661943, 47.07774412,
        59.21089531, 55.95510433, 53.60220109, 47.78062046, 45.29351182,
        33.14552449, 54.96357663, 39.19637992, 44.39575171, 49.76148334,
        62.43414349, 47.25544557, 54.54043019, 51